### PR TITLE
Fix WebRTC behaviour for Edge, upgrade Adapter.js

### PR DESCRIPTION
**Pull request by pnedonosko**
This work pretend to improve user experience for users on Microsoft Edge (v44, EdgeHTML v18). Call establishment error c004e001 should be fixed by using newer Adapter.js. Call immediate stop should be fixed by improved logic for Edge users.

### CODE REVIEW

**Comment by pnedonosko** [comment]
Referenced this PR in https://jira.exoplatform.org/browse/PLF-8777

**Comment by boubaker** [comment]
Can you please @pnedonosko make the PR on https://github.com/exo-addons/web-conferencing/

**Review by ahamdi — APPROVED** [review]
LGTM

**Review by ahamdi — CHANGES_REQUESTED** [review]
@pnedonosko I will reapprove it once moved to exo-addons

**Comment by pnedonosko** [comment]
This PR in addons repo https://github.com/exo-addons/web-conferencing/pull/44

**Pull request closed without merging**
